### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by DifferentialityDevelopment** [danikhan632/guidance_api#2]
Thank you very much for this, guidance is an amazing tool and this will massively assist in using it alongside all the goodness text-generation-webui brings together.

If you don't mind me asking, how does it integrate guidance with text-generation-webui, I have a rough idea of how guidance works but I'm totally curious how guidance is integrated into the text-generation-webui pipeline.

**Comment by danikhan632** [comment]
You enable the extension by settings as an arg like this
```
CMD_FLAGS = " --chat --model-menu  --model decapoda-research_llama-7b-hf --extensions guidance_api"
```

currently I have an Open PR to guidance
https://github.com/microsoft/guidance/pull/221

then once running you would initalize guidance like this

```
guidance.llm = guidance.llms.TGWUI("http://127.0.0.1:9555")
```

**Comment by DifferentialityDevelopment** [comment]
Awesome! 
Let's hope they can merge the PR soon :)
This will bring so much value to the whole community, guidance is incredibly useful for so so many laborious tasks.

**Comment by danikhan632** [comment]
Thank you so much for the feedback looking forward to a merged pr :)
